/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primaryBrandColor: "#3B82F6",
        secondaryAccentColor: "#60A5FA",
        backgroundLight: "#FFFFFF",
        backgroundMedium: "#F8FAFC",
        backgroundDark: "#E2E8F0",
        border: "#E2E8F0",
        textPrimary: "#1F2937",
        textSecondary: "#6B7280",
        textPlaceholder: "#9CA3AF",
        success: "#10B981",
        warning: "#F59E0B",
        danger: "#EF4444",
        info: "#60A5FA",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        'heading1': '1.5rem',
        'heading2': '1.125rem',
        'body-lg': '1rem',
        'body-md': '0.875rem',
        'body-sm': '0.75rem',
        'label': '0.875rem',
        'button': '0.875rem',
        'link': '0.875rem',
      },
      fontWeight: {
        'heading1': '600',
        'heading2': '600',
        'body-lg': '400',
        'body-md': '400',
        'body-sm': '400',
        'label': '500',
        'button': '600',
        'link': '500',
      },
      lineHeight: {
        'heading1': '2rem',
        'heading2': '1.75rem',
        'body-lg': '1.5rem',
        'body-md': '1.25rem',
        'body-sm': '1rem',
        'label': '1.25rem',
        'button': '1.25rem',
        'link': '1.25rem',
      },
      spacing: {
        'px': '1px',
        'xs': '0.25rem',
        'sm': '0.5rem',
        'md': '1rem',
        'lg': '1.5rem',
        'xl': '2rem',
        '2xl': '2.5rem',
        '3xl': '3rem',
        '4xl': '4rem',
      },
      borderRadius: {
        'sm': '0.25rem',
        'md': '0.5rem',
        'lg': '0.75rem',
        'full': '9999px',
      },
      boxShadow: {
        'light': '0px 1px 3px rgba(0, 0, 0, 0.05), 0px 1px 2px rgba(0, 0, 0, 0.05)',
        'md': '0px 4px 6px rgba(0, 0, 0, 0.1), 0px 2px 4px rgba(0, 0, 0, 0.06)',
      },
    },
  },
  plugins: [],
}
